config/routes.rb
Rails.application.routes.draw do
  namespace :snippets do
    post 'search' => 'search#index'
  end
  resources :calendar, only: [:index, :show]
  resources :post_its, except: :show
  namespace :post_its do
    get  'kanban'             => 'kanban#index'
    get  'kanban/backlog'     => 'kanban#backlog'
    get  'kanban/in_progress' => 'kanban#in_progress'
    get  'kanban/done'        => 'kanban#done'
    get  'kanban/deleted'     => 'kanban#deleted'
    get  'trash_can'     => 'trash_can#index'
    get  'parts/:id'     => 'parts#index'
    post 'parts/:id'     => 'parts#create'
    get  'parts/:id/new' => 'parts#new'
  end
  namespace :books do
    get 'kanban' => 'kanban#index'
  end
  resources :books
  get  'auth'         => 'auth#new'
  post 'auth/create'  => 'auth#create'
  get  'auth/destroy' => 'auth#destroy'
  resources :users
  resources :contents, except: [:new]
  get 'contents/:id/new' => 'contents#new'
  resources :snippets
  get '/' => 'home#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  enum status: { wish:0, backlog:1, in_progress:2, review:3, done:4, deleted:5 }
  has_many :contents
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :book
end

app/models/post_it.rb
class PostIt < ApplicationRecord
  acts_as_nested_set counter_cache: :children_count
  enum status: { backlog:0, in_progress:1, done:2, deleted:3 }
  belongs_to :user
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :snippets, dependent: :destroy
  has_many :post_its, dependent: :destroy
  validates :name,
    presence: true
  validates :password_digest,
    presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      reset_session
      session[:user] = @user.id
      redirect_to '/'
    else
      flash_reset
      render 'user'
    end
  end

  def destroy
    reset_session
    redirect_to '/'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :check_logined, only: :create
  before_action :set_book, only: [:show, :destroy, :edit, :update]
  before_action :set_contents, only: :show

  def index
    @books = Book.all.order(id: 'desc')
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "書籍を登録しました"
      redirect_to(books_kanban_path)
    else
      render(new_book_path)
    end
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "変更を保存しました"
      redirect_to(books_kanban_path)
    else
      render(new_book_path)
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_kanban_url, notice: '書籍情報を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end
    
    def set_contents
      @contents = Content.where(book_id: params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :price, :pages, :bought_at, :purpose, :status)
    end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :check_logined
  def index
    @done = PostIt.where(user_id: @user)
  end
  def show
    @date = params[:id]
    @done = PostIt.where(done_at: DateTime.parse(@date).all_day, user_id: @user)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_book, only: :new
  before_action :set_content, only: [:show, :edit]

  def index
  end

  def show
  end

  def edit
  end

  def update
    if @content.update(content_params)
      flash[:notice] = "変更を保存しました"
      redirect_to(contents_path)
    else
      render(new_content_path)
    end
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      flash[:notice] = "コンテンツを登録しました"
      redirect_to("/books/#{@content.book.id}")
    else
      render(new_content_path)
    end
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def set_content
      @content = Content.find(params[:id])
    end

    def content_params
      params.require(:content).permit(:book_id, :title, :pages)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/post_its_controller.rb
class PostItsController < ApplicationController
  before_action :check_logined, only: :create
  before_action :set_post_it, only: [:show, :destroy, :edit, :update]

  def index
    @post_its = PostIt.all
  end

  def show
  end

  def new
    @post_it = PostIt.new
  end

  def create
    @post_it = PostIt.new(post_it_params)
    if @post_it.save
      flash[:notice] = "post-itを作成しました"
      redirect_to(post_its_kanban_path)
    else
      render(new_post_it_path)
    end
  end  

  def edit
  end

  def update
    params_hash = post_it_params.to_h

    case params_hash[:status]
    when 'in_progress'
      params_hash[:in_progress_from] = DateTime.now
    when 'done'
      params_hash[:done_at]          = DateTime.now
    when 'deleted'
      params_hash[:deleted_at]       = DateTime.now
    end

    if @post_it.update(params_hash)
      flash[:notice] = "変更を保存しました"
      redirect_to(post_its_kanban_path)
    else
      render(new_post_it_path)
    end
  end

  def destroy
    @post_it.destroy
    respond_to do |format|
      format.html { redirect_to post_its_kanban_url, notice: 'ポストイットを捨てました。' }
      format.json { head :no_content }
    end
  end

  private
    def set_post_it
      @post_it = PostIt.find(params[:id])
    end

    def post_it_params
      params.require(:post_it).permit(:memo, :status, :user_id)
    end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :check_logined
  before_action :set_snippet, only: [:edit, :update]

  def index
    @snippets = Snippet.where(user_id: @user)
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)
    if @snippet.save
      flash[:notice] = "スニペットを登録しました"
      redirect_to(snippets_path)
    else
      render(new_snippet_path)
    end
  end

  def update
    if @snippet.update(snippet_params)
      flash[:notice] = "変更を保存しました"
      redirect_to(snippets_path)
    else
      render(new_snippet_path)
    end
  end

  def edit
  end

  private
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    def snippet_params
      params.require(:snippet).permit(:code, :category, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      session[:user] = @user.id
      flash[:notice] = "新規登録が完了しました。"
      redirect_to '/'
    else
      render(new_user_path)
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "変更を保存しました"
      redirect_to(users_path)
    else
      render(new_user_path)
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '書籍情報を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  private
    def current_user
      User.find(session[:user])
    rescue ActiveRecord::RecordNotFound
      false
    end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_its_helper.rb
module PostItsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_common_form.html.erb
<% if content.errors.any? %>
  <div id="error_explanation">
    <%= content.errors.full_messages do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>

<div class="field">
  <%= form.label :title, 'タイトル' %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :pages, 'ページ数' %>
  <%= form.text_field :pages %>
</div>

app/views/contents/edit.html.erb
<h1>編集</h1>

<%= form_with(model: @content, local: true) do |form| %>
  <%= render 'common_form', content: @content, form: form %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to '詳細', @content %> |
<%= link_to '戻る', :back %>

app/views/contents/index.html.erb
<h1>コンテンツ一覧</h1>
<% @contents.each do |content| %>
  <p><%= content.code %><%= link_to('編集', "/contents/#{content.id}/edit")%></p>
<% end %>

<%= link_to '戻る', url_for(:back) %>

app/views/contents/new.html.erb
<h1>コンテンツ新規登録</h1>

<%= form_with(model: @content, local: true) do |form| %>
  <%= render 'common_form', content: @content, form: form %>

  <%= form.hidden_field :book_id, value: @book.id %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', url_for(:back) %>

app/views/contents/show.html.erb
<h1><%= @content.book.title %></h1>
<h2><%= @content.title %></h2>
<p>ページ数:</p>
<p><%= @content.pages %>ページ</p>
<%= link_to('編集', edit_content_path) %> |
<%= link_to '戻る', :back %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <%= user.errors.full_messages do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, '名前' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email, 'email' %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password, 'password' %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, 'password再入力' %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>編集</h1>

<%= render 'form', user: @user %>

<%= link_to '詳細', @user %> |
<%= link_to '戻る', :back %>

app/views/users/index.html.erb
<h1>ユーザ一覧</h1>
<% @users.each do |user| %>
  <p><%= user.name %><%= link_to('編集', "/users/#{user.id}/edit")%></p>
<% end %>

<%= link_to '戻る', url_for(:back) %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', url_for(:back) %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>