config/routes.rb
Rails.application.routes.draw do
  namespace :snippets do
    post 'search' => 'search#index'
  end
  resources :calendar, only: [:index, :show]
  resources :post_its, except: :show
  namespace :post_its do
    get  'kanban'             => 'kanban#index'
    get  'kanban/backlog'     => 'kanban#backlog'
    get  'kanban/in_progress' => 'kanban#in_progress'
    get  'kanban/done'        => 'kanban#done'
    get  'kanban/deleted'     => 'kanban#deleted'
    get  'trash_can'     => 'trash_can#index'
    get  'parts/:id'     => 'parts#index'
    post 'parts/:id'     => 'parts#create'
    get  'parts/:id/new' => 'parts#new'
  end
  namespace :books do
    get 'kanban' => 'kanban#index'
  end
  resources :books
  get  'auth'         => 'auth#new'
  post 'auth/create'  => 'auth#create'
  get  'auth/destroy' => 'auth#destroy'
  resources :users
  resources :contents, except: [:new]
  get 'contents/:id/new' => 'contents#new'
  resources :snippets
  get '/' => 'home#top'
end

app/models/post_it.rb
class PostIt < ApplicationRecord
  acts_as_nested_set counter_cache: :children_count
  enum status: { backlog:0, in_progress:1, done:2, deleted:3 }
  belongs_to :user
end

app/controllers/post_its/kanban_controller.rb
class PostIts::KanbanController < ApplicationController
  before_action :check_logined
  before_action :set_backlog,       only: [:index, :backlog]
  before_action :set_in_progress,   only: [:index, :in_progress]
  before_action :set_done,          only: [:index, :done]
  before_action :destroy_old_trash, only: :deleted

  def deleted
    set_deleted
  end

  private
    def set_backlog
      @backlog = PostIt.where(status: :backlog, user_id: @user)
    end

    def set_in_progress
      @in_progress = PostIt.where(status: :in_progress, user_id: @user)
    end

    def set_done
      @done = PostIt.where(status: :done, done_at: Time.current.all_day, user_id: @user)
    end

    def set_deleted
      @deleted = PostIt.where(status: :deleted, user_id: @user)
    end

    def destroy_old_trash
      PostIt.where('status = ? and deleted_at<=?', 3, Time.current.ago(14.days)).delete_all
    end
end

app/controllers/post_its/parts_controller.rb
class PostIts::PartsController < ApplicationController
  before_action :set_parent, only: [:index, :new, :create]
  before_action :set_parts,  only: [:index, :new]

  def index
  end

  def new
    @part = PostIt.new
  end

  def create
    @part = @parent.children.new(part_params)
    if @part.save
      flash[:notice] = "子post-itを作成しました"
      redirect_to("/post_its/parts/#{@parent.id}")
    else
      render("/post_its/parts/#{@parent.id}/new")
    end
  end  

  private
    def set_parts
      @parts = PostIt.where(parent_id: @parent.id)
    end

    def set_parent
      @parent = PostIt.find(params[:id])
    end

    def part_params
      params.require(:post_it).permit(:memo, :status, :user_id)
    end
end

app/controllers/post_its/trash_can_controller.rb
class PostIts::TrashCanController < ApplicationController
  def index
    @trash = PostIt.where(status: :deleted)
  end
end

app/controllers/post_its_controller.rb
class PostItsController < ApplicationController
  before_action :check_logined, only: :create
  before_action :set_post_it, only: [:show, :destroy, :edit, :update]

  def index
    @post_its = PostIt.all
  end

  def show
  end

  def new
    @post_it = PostIt.new
  end

  def create
    @post_it = PostIt.new(post_it_params)
    if @post_it.save
      flash[:notice] = "post-itを作成しました"
      redirect_to(post_its_kanban_path)
    else
      render(new_post_it_path)
    end
  end  

  def edit
  end

  def update
    params_hash = post_it_params.to_h

    case params_hash[:status]
    when 'in_progress'
      params_hash[:in_progress_from] = DateTime.now
    when 'done'
      params_hash[:done_at]          = DateTime.now
    when 'deleted'
      params_hash[:deleted_at]       = DateTime.now
    end

    if @post_it.update(params_hash)
      flash[:notice] = "変更を保存しました"
      redirect_to(post_its_kanban_path)
    else
      render(new_post_it_path)
    end
  end

  def destroy
    @post_it.destroy
    respond_to do |format|
      format.html { redirect_to post_its_kanban_url, notice: 'ポストイットを捨てました。' }
      format.json { head :no_content }
    end
  end

  private
    def set_post_it
      @post_it = PostIt.find(params[:id])
    end

    def post_it_params
      params.require(:post_it).permit(:memo, :status, :user_id)
    end
end

app/helpers/post_its/kanban_helper.rb
module PostIts::KanbanHelper
end

app/helpers/post_its/parts_helper.rb
module PostIts::PartsHelper
end

app/helpers/post_its/trash_can_helper.rb
module PostIts::TrashCanHelper
end

app/helpers/post_its_helper.rb
module PostItsHelper
end

app/views/post_its/_form.html.erb
<%= form_with(model: post_it, local: true) do |form| %>
  <% if post_it.errors.any? %>
    <div id="error_explanation">
      <%= post_it.errors.full_messages do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>

  <% if current_user %>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  <% end %>

  <div class="field">
    <%= form.label :memo, 'メモ' %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label '思いついた', for: :post_it_status_backlog %>
    <%= form.radio_button :status, :backlog %>
    <%= form.label 'やってる', for: :post_it_status_in_progress %>
    <%= form.radio_button :status, :in_progress %>
    <%= form.label '完了した', for: :post_it_status_done %>
    <%= form.radio_button :status, :done %>
    <%= form.label 'ゴミ箱に入れる', for: :post_it_status_deleted %>
    <%= form.radio_button :status, :deleted %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_its/edit.html.erb
<h1>編集</h1>

<%= render 'form', post_it: @post_it %>

<%= link_to '詳細', @post_it %> |
<%= link_to '戻る', :back %>

app/views/post_its/index.html.erb
<h1>Post-it一覧</h1>

<%= link_to("post-it作成", new_post_it_path) %>

<% @post_its.each do |post_it| %>
  <p>
    <%= post_it.memo %>
    <%= link_to('詳細', post_it_path(post_it))%>
    <%= link_to('編集', edit_post_it_path(post_it))%>
    <%= link_to '削除', post_it, method: :delete, data: { confirm: 'このポストイットを捨ててもいいですか?' }%>
  </p>
<% end %>

<%= link_to '戻る', url_for(:back) %>

app/views/post_its/new.html.erb
<h1>post_it作成</h1>

<%= render 'form', post_it: @post_it %>

<%= link_to '戻る', url_for(:back) %>

app/views/post_its/show.html.erb
<p><%= @post_it.created_at %>作成</p>
<% unless @post_it.created_at == @post_it.updated_at %>
  <p><%= @post_it.updated_at %>最終更新</p>
<% end %>
<p><%= @post_it.memo %></p>

<%= link_to('post-it編集', edit_post_it_path) %> |
<%= link_to('分割', post_its_path(@post_it)) %> |
<%= link_to '戻る', :back %>